server:
  port: 8082

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  protocol:
    name: dubbo
    port: 20880